@extends('layouts.admin')
@section('title', 'Customers')

@section('content')
<main class="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <header class="mb-7"><p class="font-mono text-xs tracking-[.2em] text-tech-400">CUSTOMER_DIRECTORY</p><h1 class="mt-2 text-3xl font-bold text-white">Customers</h1><p class="mt-2 text-sm text-slate-400">Registered accounts, contact details, ordering activity, and confirmed customer value.</p></header>
    <section class="grid gap-3 sm:grid-cols-3"><div class="panel rounded-lg p-5"><p class="font-mono text-[10px] text-slate-500">REGISTERED_CUSTOMERS</p><strong class="mt-2 block text-2xl text-white">{{ number_format($registeredCustomers) }}</strong></div><div class="panel rounded-lg p-5"><p class="font-mono text-[10px] text-slate-500">GUEST_ORDERS</p><strong class="mt-2 block text-2xl text-amber-300">{{ number_format($guestOrders) }}</strong></div><div class="panel rounded-lg p-5"><p class="font-mono text-[10px] text-slate-500">REGISTERED_CUSTOMER_SALES</p><strong class="mt-2 block text-2xl text-emerald-300">৳{{ number_format($customerRevenue, 2) }}</strong></div></section>
    <form method="GET" action="{{ route('admin.customers') }}" class="panel mt-5 flex flex-col gap-3 rounded-lg p-4 sm:flex-row"><input name="q" value="{{ request('q') }}" placeholder="Search name, email, phone or district" class="min-w-0 flex-1 rounded border border-cyber-border bg-[#080c12] px-3 py-2.5 text-sm text-white"><button class="rounded border border-tech-500 bg-tech-700 px-5 py-2.5 text-xs font-mono text-white">SEARCH</button><a href="{{ route('admin.customers') }}" class="rounded border border-cyber-border px-5 py-2.5 text-center text-xs font-mono text-slate-300">RESET</a></form>
    <section class="panel mt-5 overflow-hidden rounded-lg"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-cyber-border bg-slate-950/60 text-[10px] font-mono text-slate-500"><tr><th class="px-4 py-3">CUSTOMER</th><th class="px-4 py-3">CONTACT</th><th class="px-4 py-3">LOCATION</th><th class="px-4 py-3">JOINED</th><th class="px-4 py-3 text-right">ORDERS</th><th class="px-4 py-3 text-right">CONFIRMED_VALUE</th><th class="px-4 py-3">LAST_ORDER</th></tr></thead><tbody class="divide-y divide-cyber-border">@forelse($customers as $customer)<tr class="hover:bg-white/[.02]"><td class="px-4 py-4"><strong class="text-white">{{ $customer->name }}</strong><span class="mt-1 block font-mono text-[9px] text-slate-600">CUSTOMER #{{ $customer->id }}</span></td><td class="px-4 py-4"><a href="mailto:{{ $customer->email }}" class="text-tech-300">{{ $customer->email }}</a><span class="mt-1 block text-xs text-slate-500">{{ $customer->phone ?: 'No phone' }}</span></td><td class="max-w-xs px-4 py-4 text-xs text-slate-400">{{ $customer->district ?: 'Not provided' }}@if($customer->address)<span class="mt-1 block truncate text-slate-600">{{ $customer->address }}</span>@endif</td><td class="whitespace-nowrap px-4 py-4 text-xs text-slate-400">{{ $customer->created_at->format('d M Y') }}</td><td class="px-4 py-4 text-right font-mono text-white">{{ $customer->orders_count }}</td><td class="px-4 py-4 text-right font-semibold text-emerald-300">৳{{ number_format((float) ($customer->lifetime_value ?? 0), 2) }}</td><td class="whitespace-nowrap px-4 py-4 text-xs text-slate-400">{{ $customer->orders_max_placed_at ? \Illuminate\Support\Carbon::parse($customer->orders_max_placed_at)->format('d M Y') : 'Never' }}</td></tr>@empty<tr><td colspan="7" class="px-5 py-12 text-center text-slate-500">No customers match this search.</td></tr>@endforelse</tbody></table></div>@if($customers->hasPages())<div class="border-t border-cyber-border px-5 py-4">{{ $customers->links() }}</div>@endif</section>
</main>
@endsection
