@extends('layouts.admin')
@section('title', 'Catalog Control')
@section('content')
<main class="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <header class="mb-8 flex flex-wrap items-end justify-between gap-4">
        <div><p class="font-mono text-xs tracking-[.2em] text-tech-400">ADMIN_CATALOG_CONTROL</p><h1 class="mt-2 text-3xl font-bold text-white">Product Registry</h1></div>
        <a href="{{ route('admin.dashboard') }}" class="inline-flex items-center gap-2 text-xs font-mono text-tech-400 hover:text-tech-300"><i data-lucide="arrow-left" class="h-4 w-4"></i>SYSTEM_CONTROL</a>
    </header>

    <section class="panel mb-7 overflow-hidden rounded-lg">
        <header class="border-b border-cyber-border px-5 py-4"><h2 class="font-mono text-sm text-white">CATEGORY_REGISTRY</h2></header>
        <div class="grid gap-5 p-5 lg:grid-cols-[.7fr_1.3fr]">
            <form method="POST" action="{{ route('admin.categories.store') }}" class="rounded-lg border border-cyber-border bg-[#080c12]/60 p-4">@csrf
                <label class="font-mono text-[10px] text-slate-400">NEW_CATEGORY_NAME<input name="name" required maxlength="120" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label>
                <button class="mt-3 rounded-lg border border-tech-400 bg-tech-600 px-4 py-2 text-xs font-mono hover:bg-tech-500">CREATE_CATEGORY</button>
            </form>
            <div class="grid gap-3 sm:grid-cols-2">@forelse($categories as $category)<article class="rounded-lg border border-cyber-border bg-[#080c12]/60 p-4"><form method="POST" action="{{ route('admin.categories.update', $category) }}" class="flex gap-2">@csrf @method('PATCH')<input name="name" value="{{ $category->name }}" maxlength="120" class="min-w-0 flex-1 rounded-lg border border-cyber-border bg-[#080c12] px-2 py-2 text-sm text-white outline-none focus:border-tech-500"><button title="Rename category" class="grid h-9 w-9 place-items-center rounded-lg border border-tech-600 text-tech-300 hover:bg-tech-600 hover:text-white"><i data-lucide="save" class="h-4 w-4"></i></button></form><div class="mt-3 flex items-center justify-between"><span class="font-mono text-[10px] text-slate-500">{{ $category->products_count }} PRODUCT(S)</span><form method="POST" action="{{ route('admin.categories.destroy', $category) }}" onsubmit="return confirm('Delete this empty category?')">@csrf @method('DELETE')<button title="Delete empty category" class="text-xs font-mono text-rose-300 hover:text-rose-200">DELETE</button></form></div></article>@empty<p class="text-sm text-slate-500">Create at least one category before registering a product.</p>@endforelse</div>
        </div>
    </section>

    <div class="grid gap-7 lg:grid-cols-[.9fr_1.1fr]">
        <form method="POST" action="{{ route('admin.products.store') }}" enctype="multipart/form-data" class="panel h-fit rounded-lg p-5">@csrf
            <h2 class="font-mono text-sm text-tech-300">REGISTER_NEW_UNIT</h2>
            <div class="mt-5 grid gap-4">
                <label class="font-mono text-[10px] text-slate-400">UNIT_NAME<input name="name" required value="{{ old('name') }}" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label>
                <label class="font-mono text-[10px] text-slate-400">CATEGORY<select name="category_id" required class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id') == $category->id)>{{ $category->name }}</option>@endforeach</select></label>
                <div class="grid grid-cols-2 gap-3"><label class="font-mono text-[10px] text-slate-400">PRICE_BDT<input type="number" name="price" min="0" step="0.01" required value="{{ old('price') }}" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label><label class="font-mono text-[10px] text-slate-400">COMPARE_AT_BDT<input type="number" name="compare_at_price" min="0" step="0.01" value="{{ old('compare_at_price') }}" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label></div>
                <div class="grid grid-cols-2 gap-3"><label class="font-mono text-[10px] text-slate-400">DISCOUNT_PERCENT<input type="number" name="discount_percent" min="0" max="100" step="1" value="{{ old('discount_percent', 0) }}" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label><label class="font-mono text-[10px] text-slate-400">STOCK<input type="number" name="stock" min="0" required value="{{ old('stock', 0) }}" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label></div>
                <div class="grid grid-cols-2 gap-3"><label class="font-mono text-[10px] text-slate-400">STATUS<select name="status" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"><option value="active">ACTIVE</option><option value="draft">DRAFT</option><option value="archived">ARCHIVED</option></select></label><label class="flex items-center gap-2 rounded-lg border border-cyber-border bg-[#080c12] px-3 py-3 text-sm text-slate-300"><input type="checkbox" name="is_featured" value="1" class="accent-teal-500">Feature on storefront</label></div>
                <label class="font-mono text-[10px] text-slate-400">DESCRIPTION<textarea name="description" rows="4" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500">{{ old('description') }}</textarea></label>
                <label class="font-mono text-[10px] text-slate-400">SEO_TITLE<input name="seo_title" value="{{ old('seo_title') }}" maxlength="255" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label>
                <label class="font-mono text-[10px] text-slate-400">SEO_DESCRIPTION<textarea name="seo_description" rows="3" maxlength="500" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500">{{ old('seo_description') }}</textarea></label>
                <fieldset class="rounded-lg border border-tech-800 bg-tech-950/30 p-4"><legend class="px-1 font-mono text-[10px] text-tech-300">MEDIA_UPLOAD</legend><label class="mt-2 block font-mono text-[10px] text-slate-400">PRODUCT_PHOTOS <span class="text-slate-500">MAX 7 / 5 MB EACH</span><input type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple class="mt-2 block w-full text-xs text-slate-400 file:mr-3 file:border-0 file:bg-tech-600 file:px-3 file:py-2 file:font-mono file:text-xs file:text-white"></label><label class="mt-4 block font-mono text-[10px] text-slate-400">PRODUCT_VIDEO <span class="text-slate-500">ONE FILE / MAX 100 MB</span><input type="file" name="video" accept="video/mp4,video/webm,video/quicktime" class="mt-2 block w-full text-xs text-slate-400 file:mr-3 file:border-0 file:bg-tech-600 file:px-3 file:py-2 file:font-mono file:text-xs file:text-white"></label></fieldset>
                <button class="rounded-lg border border-tech-400 bg-tech-600 p-3 text-sm font-mono hover:bg-tech-500">COMMIT_PRODUCT</button>
            </div>
        </form>

        <section class="space-y-5">
            <header class="flex items-center justify-between"><h2 class="font-mono text-sm text-white">CATALOG_STREAM</h2><span class="font-mono text-[10px] text-slate-500">{{ $products->total() }} UNITS</span></header>
            @forelse($products as $product)
                <article class="panel overflow-hidden rounded-lg">
                    <header class="flex flex-wrap items-center justify-between gap-3 border-b border-cyber-border bg-[#080c12]/50 px-5 py-4"><div><p class="font-mono text-[10px] text-tech-400">{{ $product->sku }}</p><h3 class="mt-1 font-semibold text-white">{{ $product->name }}</h3></div><form method="POST" action="{{ route('admin.products.destroy', $product) }}" onsubmit="return confirm('Delete {{ addslashes($product->name) }} and all uploaded media?')">@csrf @method('DELETE')<button class="inline-flex items-center gap-2 rounded-lg border border-rose-900 px-3 py-2 text-xs font-mono text-rose-300 hover:bg-rose-950"><i data-lucide="trash-2" class="h-4 w-4"></i>DELETE_PRODUCT</button></form></header>
                    <form method="POST" action="{{ route('admin.products.update', $product) }}" enctype="multipart/form-data" class="p-5">@csrf @method('PATCH')
                        <input type="hidden" name="is_featured" value="0">
                        <div class="grid gap-4 sm:grid-cols-2">
                            <label class="font-mono text-[10px] text-slate-400">UNIT_NAME<input name="name" required value="{{ $product->name }}" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label>
                            <label class="font-mono text-[10px] text-slate-400">CATEGORY<select name="category_id" required class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500">@foreach($categories as $category)<option value="{{ $category->id }}" @selected($product->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select></label>
                            <label class="font-mono text-[10px] text-slate-400">ORIGINAL_PRICE_BDT<input type="number" name="price" min="0" step="0.01" required value="{{ $product->price }}" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label>
                            <label class="font-mono text-[10px] text-slate-400">DISCOUNT_PERCENT<input type="number" name="discount_percent" min="0" max="100" step="1" value="{{ $product->discountPercent() }}" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label>
                            <input type="hidden" name="compare_at_price" value="{{ $product->compare_at_price }}">
                            <label class="font-mono text-[10px] text-slate-400">TOTAL_STOCK<input type="number" name="stock" min="0" required value="{{ $product->stock }}" @disabled(count($product->purchasableVariants()) > 0) class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500 disabled:opacity-60"></label>
                            <label class="font-mono text-[10px] text-slate-400">STATUS<select name="status" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500">@foreach(['active','draft','archived'] as $status)<option value="{{ $status }}" @selected($product->status === $status)>{{ strtoupper($status) }}</option>@endforeach</select></label>
                            <label class="flex items-center gap-2 rounded-lg border border-cyber-border bg-[#080c12] px-3 py-3 text-sm text-slate-300"><input type="checkbox" name="is_featured" value="1" @checked($product->is_featured) class="accent-teal-500">Feature on storefront</label>
                            <label class="font-mono text-[10px] text-slate-400">SELLING_PRICE<input disabled value="BDT {{ number_format($product->final_price, 2) }}" class="mt-2 w-full rounded-lg border border-tech-800 bg-tech-950/40 p-3 text-sm text-tech-200"></label>
                        </div>
                        <label class="mt-4 block font-mono text-[10px] text-slate-400">DESCRIPTION<textarea name="description" rows="3" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500">{{ $product->description }}</textarea></label>
                        <fieldset class="mt-4 rounded-lg border border-cyber-border p-4"><legend class="px-1 font-mono text-[10px] text-tech-300">COMMERCIAL_SPECIFICATIONS</legend><div class="space-y-2">@foreach(($product->specs ?? []) as $key => $value)<div class="grid gap-2 sm:grid-cols-2"><input name="spec_keys[]" value="{{ $key }}" placeholder="Specification" class="rounded border border-cyber-border bg-[#080c12] p-2 text-sm text-white"><input name="spec_values[]" value="{{ $value }}" placeholder="Value" class="rounded border border-cyber-border bg-[#080c12] p-2 text-sm text-white"></div>@endforeach @for($row = 0; $row < 3; $row++)<div class="grid gap-2 sm:grid-cols-2"><input name="spec_keys[]" placeholder="Add specification" class="rounded border border-cyber-border bg-[#080c12] p-2 text-sm text-white"><input name="spec_values[]" placeholder="Value" class="rounded border border-cyber-border bg-[#080c12] p-2 text-sm text-white"></div>@endfor</div></fieldset>
                        <fieldset class="mt-4 rounded-lg border border-cyber-border p-4"><legend class="px-1 font-mono text-[10px] text-tech-300">PURCHASABLE_COLORS</legend><div class="grid gap-3 sm:grid-cols-2">@foreach(['black' => 'Black', 'white' => 'White'] as $key => $label)@php($variant = collect($product->purchasableVariants())->firstWhere('key', $key))<div class="rounded border border-cyber-border bg-[#080c12] p-3"><input type="hidden" name="variants[{{ $key }}][label]" value="{{ $label }}"><label class="flex items-center gap-2 text-sm"><input type="hidden" name="variants[{{ $key }}][available]" value="0"><input type="checkbox" name="variants[{{ $key }}][available]" value="1" @checked($variant['available'] ?? false)> {{ $label }} available</label><label class="mt-2 block text-xs text-slate-400">Stock<input type="number" name="variants[{{ $key }}][stock]" min="0" value="{{ $variant['stock'] ?? 0 }}" class="mt-1 w-full rounded border border-cyber-border bg-slate-950 p-2 text-white"></label></div>@endforeach</div><p class="mt-3 text-xs text-slate-500">Total storefront stock is calculated from enabled color stock.</p></fieldset>
                        <div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="font-mono text-[10px] text-slate-400">SEO_TITLE<input name="seo_title" value="{{ $product->seo_title }}" maxlength="255" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500"></label><label class="font-mono text-[10px] text-slate-400">SEO_DESCRIPTION<textarea name="seo_description" rows="3" maxlength="500" class="mt-2 w-full rounded-lg border border-cyber-border bg-[#080c12] p-3 text-sm text-white outline-none focus:border-tech-500">{{ $product->seo_description }}</textarea></label></div>
                        <fieldset class="mt-4 rounded-lg border border-cyber-border p-4"><legend class="px-1 font-mono text-[10px] text-tech-300">MEDIA_LIBRARY</legend><div data-image-order class="grid grid-cols-2 gap-3 sm:grid-cols-4">@forelse($product->images ?? [] as $image)<div data-image-item class="relative overflow-hidden rounded-lg border border-cyber-border bg-[#080c12]"><input type="hidden" name="image_order[]" value="{{ $image }}"><img src="{{ Illuminate\Support\Facades\Storage::disk('public')->exists($image) ? Illuminate\Support\Facades\Storage::disk('public')->url($image) : $product->primaryImageUrl() }}" alt="{{ $product->name }} preview" class="aspect-square w-full object-contain"><div class="flex items-center justify-between bg-black/80 p-2"><span class="flex gap-1"><button type="button" data-image-move="up" title="Move earlier" class="px-2 text-tech-300">←</button><button type="button" data-image-move="down" title="Move later" class="px-2 text-tech-300">→</button></span><label class="font-mono text-[9px] text-rose-200"><input type="checkbox" name="remove_images[]" value="{{ $image }}"> REMOVE</label></div></div>@empty<div class="col-span-full"><img src="{{ $product->primaryImageUrl() }}" alt="{{ $product->name }} representative image" class="h-36 w-full max-w-xs object-contain"><p class="mt-2 text-xs text-slate-500">No uploaded product photos. The permanent catalog fallback is shown.</p></div>@endforelse</div><label class="mt-4 block font-mono text-[10px] text-slate-400">ADD_PHOTOS <span class="text-slate-500">FINAL LIMIT 7 / 5 MB EACH</span><input type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple class="mt-2 block w-full text-xs text-slate-400 file:mr-3 file:border-0 file:bg-tech-600 file:px-3 file:py-2 file:font-mono file:text-xs file:text-white"></label><div class="mt-4 border-t border-cyber-border pt-4">@if($product->videoUrl())<video controls preload="metadata" class="w-full max-w-md rounded-lg border border-cyber-border" src="{{ $product->videoUrl() }}"></video><label class="mt-2 flex items-center gap-2 font-mono text-[10px] text-rose-200"><input type="checkbox" name="remove_video" value="1">REMOVE_CURRENT_VIDEO</label>@else<p class="text-xs text-slate-500">No product video uploaded.</p>@endif<label class="mt-3 block font-mono text-[10px] text-slate-400">REPLACE_VIDEO <span class="text-slate-500">ONE FILE / MAX 100 MB</span><input type="file" name="video" accept="video/mp4,video/webm,video/quicktime" class="mt-2 block w-full text-xs text-slate-400 file:mr-3 file:border-0 file:bg-tech-600 file:px-3 file:py-2 file:font-mono file:text-xs file:text-white"></label></div></fieldset>
                        <button class="mt-5 inline-flex items-center gap-2 rounded-lg border border-tech-400 bg-tech-600 px-4 py-3 text-sm font-mono hover:bg-tech-500"><i data-lucide="save" class="h-4 w-4"></i>SYNC_PRODUCT</button>
                    </form>
                </article>
            @empty
                <div class="panel rounded-lg p-8 text-center text-slate-500">The product catalog is empty. Add the first product.</div>
            @endforelse
            <div>{{ $products->links() }}</div>
        </section>
    </div>
</main>
@endsection
